### ISSUE TITLE
[Issue] There's no "latest" tag for the Docker image

### ISSUE THREAD

**Issue by vp-en** [mornedhels/icarus-server#5]
**[Issue] There's no "latest" tag for the Docker image**

Hey there! And thanks a lot for this image, and making it run under a supervisor <3

**The issue**
Basically just the title, no `latest` tag available for the docker image. 
Which results in the [docker-compose example](https://github.com/mornedhels/icarus-server#docker-compose) not working, since only `dev` is available as the tag for the image.

**Comment by cp-fabian-pittroff** [comment]
Hey @vp-en,

thanks for using this image. I wanted to test the cleanup before releasing the first version.
For now, it is only logging which files it would delete.

I can build a first 0.x version, so the latest tag is working, but there might be changes to environment variables or something in the future.

**Comment by cp-fabian-pittroff** [comment]
Released Version **[0.1.0](https://github.com/mornedhels/icarus-server/releases/tag/0.1.0)**. Docker latest tag is now available.

If there is something else, feel free to reopen or create another issue.
