### ISSUE TITLE
CLEANUP_EXCLUDES excludes every file by default

### ISSUE THREAD

**Issue by Kyle0654** [mornedhels/icarus-server#52]
This line defaults the regex to ``, which matches every file by default.

https://github.com/mornedhels/icarus-server/blob/06410df213593b8e46930a34080cd757f8db5e95/scripts/defaults#L30

Defaulting this to `^$` or even `.*` would work as expected (nothing is excluded by default).

**Comment by cp-fabian-pittroff** [comment]
Hey @Kyle0654, thanks for the report. I included the fix (^$) and it is available with the latest dev image.
